import type { Metadata } from "next";
import { Fragment_Mono, Plus_Jakarta_Sans } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import ReactLenis from "lenis/react";
import { LayoutProvider } from "@/contexts/LayoutContext";
import LayoutContent from "@/components/layout/LayoutContent";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  display: "swap",
});

const fragmentMono = Fragment_Mono({
  variable: "--font-fragment-mono",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${fragmentMono.variable} antialiased`}
      >
        <ReactLenis root>
          <LayoutProvider>
            <LayoutContent>
              {children}
              <SpeedInsights />
            </LayoutContent>
          </LayoutProvider>
        </ReactLenis>
      </body>
    </html>
  );
}
